name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3

    - name: Install dependencies
      run: npm ci

    - name: Bump version
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        npm version patch -m "Bump to %s"
        git push

    - name: Build app
      run: npm run build

    - name: Get version
      id: packagejson
      uses: martinbeentjes/npm-get-version-action@v1.1.0

    - name: Create Release
      run: cd build && zip -r ../IPCamViewer-${{ steps.packagejson.outputs.current-version }}.zip *
      id: create_release

    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: 'IPCamViewer-${{ steps.packagejson.outputs.current-version }}.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.packagejson.outputs.current-version }}